### ISSUE TITLE
Where is mapbox.json file

### ISSUE THREAD

**Issue by hakan9462** [terranodo/tegola-openseamap#28]
Hello,

Where ist the mapbox.json file ? I can not find it. 
can someone help me?

**Comment by erictheise** [comment]
It's been a couple-plus years, @hakan9462, but the file you're looking for is at [`~/docs/nautical_active.json`](https://raw.githubusercontent.com/go-spatial/tegola-openseamap/master/docs/nautical_active.json). I believe we did that so that it would show up in a GitHub Pages-based site and that was the architecture at the time.
